name: Docs to Html

on:
  push:
    paths:
      - '**.md'

jobs:
  converttohtml:
    name: Build Html
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: BaileyJM02/markdown-to-pdf@v1.2.0
        with:
          input_path: README.md
          build_html: true
          build_pdf: false
      - uses: actions/upload-artifact@v3
        with:
          name: README.html
