name: Docs to Html

on:
  push:
    paths:
      - '**.md'

jobs:
  converttohtml:
    name: Build Html
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: BaileyJM02/markdown-to-pdf@v1.2.0
        with:
          input_path: README.md
          build_html: true
      - name: Move
        run: mv README.html index.html
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: convert to html
